services:
  db:
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/00-init.sql:ro

  backend:
    environment:
      DJANGO_DEBUG: ${DJANGO_DEBUG:-0}
    volumes: []

