# Generated by Django 5.2.12 on 2026-03-19 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_slug', models.CharField(db_index=True, max_length=64)),
                ('base_link', models.URLField(blank=True, max_length=2000, null=True)),
                ('request_url', models.URLField(max_length=2000, unique=True)),
                ('townfrom', models.CharField(blank=True, db_index=True, max_length=128)),
                ('adult', models.PositiveSmallIntegerField(db_index=True, default=1)),
                ('child', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('night_min', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True)),
                ('night_max', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True)),
                ('checkin_beg', models.DateField(blank=True, db_index=True, null=True)),
                ('checkin_end', models.DateField(blank=True, db_index=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('trip_dates', models.TextField(blank=True)),
                ('nights', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True)),
                ('room', models.CharField(blank=True, db_index=True, max_length=255)),
                ('meal', models.CharField(blank=True, db_index=True, max_length=128)),
                ('placement', models.CharField(blank=True, db_index=True, max_length=255)),
                ('price_text', models.CharField(blank=True, max_length=64)),
                ('price_value', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('booking_link', models.URLField(blank=True, max_length=2000, null=True)),
                ('raw_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amenities', models.ManyToManyField(blank=True, related_name='tours', to='tours.amenity')),
            ],
            options={
                'ordering': ['price_value', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='tours.tour')),
            ],
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['price_value', 'country_slug'], name='tours_tour_price_v_04d9e7_idx'),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['checkin_beg', 'checkin_end'], name='tours_tour_checkin_6fe09b_idx'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'tour'), name='uniq_user_tour_fav'),
        ),
    ]
