# Generated by Django 5.2.12 on 2026-03-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='hotel_category',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
