# Generated by Django 5.2.12 on 2026-03-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_tour_hotel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='request_url',
            field=models.URLField(db_index=True, max_length=2000),
        ),
        migrations.AddConstraint(
            model_name='tour',
            constraint=models.UniqueConstraint(condition=models.Q(('booking_link__isnull', False)), fields=('booking_link',), name='uniq_tour_booking_link'),
        ),
    ]
