# Generated by Django 5.2.12 on 2026-03-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_alter_tour_request_url_tour_uniq_tour_booking_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='hotel_type',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AddField(
            model_name='tour',
            name='rest_type',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
    ]
