# Generated by Django 5.2.12 on 2026-03-23 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_tour_hotel_type_tour_rest_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha256', models.CharField(max_length=64, unique=True)),
                ('content', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='tour',
            name='description',
        ),
        migrations.AddField(
            model_name='tour',
            name='hotel_name',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tour',
            name='hotel_rating',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='tour',
            name='hotel_stars',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='main_image_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='common_description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='common_for', to='tours.tourtext'),
        ),
        migrations.AddField(
            model_name='tour',
            name='target_description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_for', to='tours.tourtext'),
        ),
    ]
